@root enpoint

GET http://localhost:3000

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "chuilanzheng",
    "email": "chuilanzheng@gmail.com",
    "password": "12345678",
    "fullname": "Cui Lan Zheng"
}

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    
    "email": "rezkymuflih@gmail.com",
    "password": "12345678"
}

GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczMzkzMDgzLCJleHAiOjE3NzM5MTE0ODN9.U-JbrM7N3-6pxve6e5QiSqqU5CJ4rU7yHpShat9wSvI

GET http://localhost:3000/api/user/rezky123

GET http://localhost:3000/api/user/search?username=rezky

PUT http://localhost:3000/api/user/update-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczMzkzMDgzLCJleHAiOjE3NzM5MTE0ODN9.U-JbrM7N3-6pxve6e5QiSqqU5CJ4rU7yHpShat9wSvI
Content-Type: application/json

{
    
    "bio": "saya adalah rezky muflih, seorang mahasiswa yang sedang belajar pemrograman",
    "fullname": "Rezky Muflih Mubarok",
    "username": "rezkymuflih"
}

PUT http://localhost:3000/api/user/update-photo-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczMzkzMDgzLCJleHAiOjE3NzM5MTE0ODN9.U-JbrM7N3-6pxve6e5QiSqqU5CJ4rU7yHpShat9wSvI
Content-Type: multipart/form-data
Key: image
Value: (select file)

POST http://localhost:3000/api/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczNDcyMzMwLCJleHAiOjE3NzM5OTA3MzB9.MvGnmqZz8reVnNmlWuphBENYDSqb7iaS-qAjvwfT-fg
Content-Type: application/json

{
    "followUserId": 8
}

DELETE  http://localhost:3000/api/follow/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczODA2MzU2LCJleHAiOjE3NzQzMjQ3NTZ9.cucirJlPDSEfhL6zeOPMpHdpGMtamiN0kbj3AgGw5aI

GET  http://localhost:3000/api/follow/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzczODA2MzU2LCJleHAiOjE3NzQzMjQ3NTZ9.cucirJlPDSEfhL6zeOPMpHdpGMtamiN0kbj3AgGw5aI